runtime: nodejs20
service: server

env_variables:
  DB_socketPath: "/ultra-mediator-423907-a4:us-central1:atlascopcos"
  DB_USERNAME: "atlascopco_admin"
  DB_PASSWORD: "10028mike."
  DATABASE: "AtlasCopco"
  NODE_ENV: "production"

beta_settings:
  cloud_sql_instances: "ultra-mediator-423907-a4:us-central1:atlascopcos"
