runtime: nodejs16
instance_class: F2
env_variables:
  NODE_ENV: 'production'
  GOOGLE_CLIENT_ID: 'your-google-client-id'
  INSTANCE_HOST: 'your-database-host'
  DB_USERNAME: 'your-database-username'
  DB_PASSWORD: 'your-database-password'
  DATABASE: 'your-database-name'
  DB_PORT: 'your-database-port'
